local go = require("go")
vim.keymap.set("n", "<Leader>ta", go.test_all)
vim.keymap.set("n", "<Leader>tA", go.test_all_nocache)
vim.keymap.set("n", "<Leader>tr", go.test_nearest)
vim.keymap.set("n", "<Leader>tR", go.test_nearest_nocache)
vim.keymap.set("n", "<Leader>tf", go.test_function)
vim.keymap.set("n", "<Leader>tF", go.test_function_nocache)
vim.keymap.set("n", "<Leader>tl", go.test_last)
vim.keymap.set("n", "<Leader>td", go.debug_nearest_test)
