#!/usr/bin/env python3

import argparse
import glob
import os
import shutil

home = os.path.expanduser("~")


def globfiles(dir: str) -> filter[str]:
    all = glob.iglob(dir + "/**/*", recursive=True, include_hidden=True)
    return filter(os.path.isfile, all)


def copy(src: str, dst: str):
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    shutil.copy(src, dst, follow_symlinks=False)


def add(args: argparse.Namespace):
    dir: str = os.path.normpath(args.dir)
    for file in [str(os.path.expanduser(os.path.normpath(f))) for f in args.files]:
        if os.path.isfile(file):
            copy(file, file.replace(home, dir, 1))
        elif os.path.isdir(file):
            for file2 in globfiles(file):
                copy(file2, file2.replace(home, dir, 1))
        else:
            raise SystemExit(f"'{file}' doesn't exist!")


def readd(args: argparse.Namespace):
    for dir in map(os.path.normpath, list[str](args.dirs)):
        for file in globfiles(dir):
            try:
                copy(file.replace(dir, home, 1), file)
            except FileNotFoundError:
                os.remove(file)
                try:
                    os.removedirs(os.path.dirname(file))
                except OSError:
                    pass


def apply(args: argparse.Namespace):
    for dir in map(os.path.normpath, list[str](args.dirs)):
        if not os.path.isdir(dir):
            raise SystemExit(f"'{dir}' directory doesn't exist!")
        for file in globfiles(dir):
            copy(file, file.replace(dir, home, 1))


parser = argparse.ArgumentParser()
subparsers = parser.add_subparsers(title="subcommands", required=True)

parser_add = subparsers.add_parser("add")
parser_add.add_argument("dir", type=str)
parser_add.add_argument("files", type=str, nargs="+")
parser_add.set_defaults(func=add)

parser_readd = subparsers.add_parser("readd")
parser_readd.add_argument("dirs", type=str, nargs="+")
parser_readd.set_defaults(func=readd)

parser_apply = subparsers.add_parser("apply")
parser_apply.add_argument("dirs", type=str, nargs="+")
parser_apply.set_defaults(func=apply)

args = parser.parse_args()
args.func(args)
