-- Based on https://github.com/vague2k/vague.nvim

local c = {
	bg = "#141415",
	fg = "#cdcdcd",
	line = "#252530",
	comment = "#606079",
	special = "#b4d4cf",
	func = "#c48282",
	string = "#e8b589",
	constant = "#aeaed1",
	call = "#bb9dbd",
	visual = "#333738",
	error = "#d8647e",
	warning = "#f3be7c",
	keyword = "#6e94b2",
	type = "#9bb4bc",
	search = "#405065",
	plus = "#7fa563",
}

local function color_to_rgb(color)
	local function byte(value, offset) return bit.band(bit.rshift(value, offset), 0xFF) end

	local new_color = vim.api.nvim_get_color_by_name(color)
	if new_color == -1 then new_color = 000 end

	return { byte(new_color, 16), byte(new_color, 8), byte(new_color, 0) }
end

local function blend(color, base_color, alpha)
	local fg_rgb = color_to_rgb(color)
	local bg_rgb = color_to_rgb(base_color)

	local function blend_channel(i)
		local ret = (alpha * fg_rgb[i] + ((1 - alpha) * bg_rgb[i]))
		return math.floor(math.min(math.max(0, ret), 255) + 0.5)
	end

	local result = string.format("#%02X%02X%02X", blend_channel(1), blend_channel(2), blend_channel(3))

	return result
end

local set = vim.api.nvim_set_hl

-- Built in
set(0, "@attribute", { link = "Constant" })
set(0, "@boolean", { link = "Boolean" })
set(0, "@character", { link = "String" })
set(0, "@constant", { link = "Constant" })
set(0, "@constructor", { link = "Constant" })
set(0, "@diff.delta", { link = "Changed" })
set(0, "@diff.minus", { link = "Removed" })
set(0, "@diff.plus", { link = "Added" })
set(0, "@function.call", { fg = c.call })
set(0, "@function.method.call", { link = "@function.call" })
set(0, "@keyword", { link = "Keyword" })
set(0, "@keyword.exception", { link = "Exception" })
set(0, "@keyword.import", { link = "PreProc" })
set(0, "@label", { link = "Label" })
set(0, "@markup", { link = "@variable" })
set(0, "@markup.heading", { fg = c.keyword, bold = true })
set(0, "@markup.italic", { fg = c.fg, italic = true })
set(0, "@markup.link", { link = "String" })
set(0, "@markup.link.uri", { fg = c.string, underline = true })
set(0, "@markup.list", { link = "Function" })
set(0, "@markup.math", { link = "String" })
set(0, "@markup.quote.markdown", { link = "NonText" })
set(0, "@markup.raw", { link = "Constant" })
set(0, "@markup.strikethrough", { fg = c.comment, strikethrough = true })
set(0, "@markup.strong", { link = "Title" })
set(0, "@markup.underline", { fg = c.fg, underline = true })
set(0, "@module", { link = "Constant" })
set(0, "@number", { link = "Number" })
set(0, "@operator", { link = "Operator" })
set(0, "@property", { link = "@variable.member" })
set(0, "@punctuation.special", { link = "SpecialChar" })
set(0, "@string", { link = "String" })
set(0, "@string.documentation", { link = "Comment" })
set(0, "@string.escape", { link = "SpecialChar" })
set(0, "@string.regexp", { link = "SpecialChar" })
set(0, "@string.special.symbol", { link = "Identifier" })
set(0, "@string.special.url", { link = "Function" })
set(0, "@tag.attribute", { link = "Identifier" })
set(0, "@tag.delimiter", { link = "@variable" })
set(0, "@text.diff.add", { link = "DiffAdd" })
set(0, "@text.diff.delete", { link = "DiffDelete" })
set(0, "@type", { link = "Type" })
set(0, "@variable", { fg = c.fg })
set(0, "@variable.builtin", { link = "Special" })
set(0, "@variable.member", { link = "Special" })
set(0, "Added", { fg = c.plus })
set(0, "Boolean", { link = "Number" })
set(0, "Changed", { fg = c.warning })
set(0, "Character", { link = "String" })
set(0, "ColorColumn", { link = "CursorLine" })
set(0, "Comment", { fg = c.comment, italic = true })
set(0, "Conceal", { fg = c.func, bg = c.bg })
set(0, "Conditional", { link = "Statement" })
set(0, "Constant", { fg = c.constant })
set(0, "CurSearch", { link = "Search" })
set(0, "CursorColumn", { link = "CursorLine" })
set(0, "CursorLine", { bg = c.line })
set(0, "CursorLineNr", { link = "@variable" })
set(0, "Debug", { link = "Constant" })
set(0, "Define", { link = "NonText" })
set(0, "Delimiter", { link = "@variable" })
set(0, "DiagnosticDeprecated", { fg = c.error, strikethrough = true })
set(0, "DiagnosticError", { link = "Removed" })
set(0, "DiagnosticHint", { fg = c.special })
set(0, "DiagnosticInfo", { link = "Constant" })
set(0, "DiagnosticOk", { link = "Added" })
set(0, "DiagnosticUnderlineError", { undercurl = true, sp = c.error })
set(0, "DiagnosticUnderlineHint", { undercurl = true, sp = c.special })
set(0, "DiagnosticUnderlineInfo", { undercurl = true, sp = c.constant })
set(0, "DiagnosticUnderlineOk", { undercurl = true, sp = c.plus })
set(0, "DiagnosticUnderlineWarn", { undercurl = true, sp = c.warning })
set(0, "DiagnosticVirtualTextError", { link = "Removed" })
set(0, "DiagnosticVirtualTextHint", { link = "DiagnosticHint" })
set(0, "DiagnosticVirtualTextInfo", { link = "Constant" })
set(0, "DiagnosticVirtualTextOk", { link = "Added" })
set(0, "DiagnosticVirtualTextWarn", { link = "DiagnosticWarn" })
set(0, "DiagnosticWarn", { fg = c.warning })
set(0, "DiffAdd", { bg = blend(c.plus, c.bg, 0.2) })
set(0, "DiffChange", { bg = blend(c.warning, c.bg, 0.1) })
set(0, "DiffDelete", { bg = blend(c.error, c.bg, 0.2) })
set(0, "DiffFile", { link = "Statement" })
set(0, "DiffIndexLine", { link = "NonText" })
set(0, "DiffText", { bg = blend(c.warning, c.bg, 0.3) })
set(0, "Directory", { link = "Statement" })
set(0, "EndOfBuffer", { link = "NonText" })
set(0, "Error", { fg = c.error, bold = true })
set(0, "ErrorMsg", { link = "Error" })
set(0, "Exception", { link = "Statement" })
set(0, "FloatBorder", { link = "NonText" })
set(0, "FloatFooter", { link = "FloatBorder" })
set(0, "FloatTitle", { link = "FloatBorder" })
set(0, "FoldColumn", { fg = c.comment, bg = c.bg })
set(0, "Folded", { fg = c.comment, bg = c.line })
set(0, "Function", { fg = c.func })
set(0, "Identifier", { link = "Constant" })
set(0, "IncSearch", { fg = c.bg, bg = c.warning })
set(0, "Include", { link = "Statement" })
set(0, "Keyword", { fg = c.keyword, italic = true })
set(0, "Label", { link = "Statement" })
set(0, "LineNr", { link = "NonText" })
set(0, "LspCodeLens", { fg = c.comment, italic = true })
set(0, "LspCodeLensSeparator", { link = "NonText" })
set(0, "LspReferenceRead", { bg = c.comment })
set(0, "LspReferenceText", { bg = c.comment })
set(0, "LspReferenceWrite", { bg = c.comment })
set(0, "Macro", { link = "Constant" })
set(0, "MatchParen", { fg = c.fg, bg = c.visual })
set(0, "ModeMsg", { link = "String" })
set(0, "MoreMsg", { fg = c.func, bold = true })
set(0, "MsgSeparator", { fg = c.string, bg = c.line, bold = true })
set(0, "NonText", { fg = c.comment })
set(0, "Normal", { fg = c.fg, bg = c.bg })
set(0, "NormalFloat", { link = "Normal" })
set(0, "Number", { fg = c.string })
set(0, "OkMsg", { link = "Added" })
set(0, "Operator", { fg = c.type })
set(0, "Pmenu", { link = "Normal" })
set(0, "PmenuBorder", { link = "FloatBorder" })
set(0, "PmenuSbar", { fg = c.visual, bg = c.comment })
set(0, "PmenuSel", { fg = c.constant, bg = c.line })
set(0, "PmenuThumb", { fg = c.comment, bg = c.visual })
set(0, "PreCondit", { link = "NonText" })
set(0, "PreProc", { link = "Function" })
set(0, "Question", { link = "Constant" })
set(0, "QuickFixLine", { link = "CursorLine" })
set(0, "Removed", { fg = c.error })
set(0, "Repeat", { link = "Statement" })
set(0, "Search", { fg = c.fg, bg = c.search })
set(0, "SignColumn", { link = "@variable" })
set(0, "Special", { fg = c.special })
set(0, "SpecialChar", { link = "Statement" })
set(0, "SpecialComment", { link = "Statement" })
set(0, "SpecialKey", { link = "NonText" })
set(0, "Statement", { fg = c.keyword })
set(0, "StatusLine", { fg = c.bg, bg = c.keyword })
set(0, "StatusLineNC", { fg = c.fg, bg = c.visual })
set(0, "StatusLineTerm", { link = "StatusLine" })
set(0, "StatusLineTermNC", { link = "StatusLineNC" })
set(0, "StorageClass", { link = "Constant" })
set(0, "String", { fg = c.string })
set(0, "Structure", { link = "Constant" })
set(0, "Substitute", { fg = c.type, bg = c.visual })
set(0, "TabLine", { link = "Normal" })
set(0, "TabLineFill", { fg = c.comment, bg = c.bg })
set(0, "TabLineSel", { fg = c.bg, bg = c.fg })
set(0, "Tag", { link = "Special" })
set(0, "Terminal", { link = "Normal" })
set(0, "Title", { fg = c.fg, bold = true })
set(0, "Todo", { fg = c.func, italic = true })
set(0, "ToolbarButton", { fg = c.bg, bg = c.visual })
set(0, "ToolbarLine", { link = "@variable" })
set(0, "Type", { fg = c.type })
set(0, "Typedef", { link = "Constant" })
set(0, "Visual", { bg = c.visual })
set(0, "VisualNOS", { bg = c.comment, underline = true })
set(0, "WarningMsg", { fg = c.warning, bold = true })
set(0, "Whitespace", { fg = blend(c.comment, c.bg, 0.3) })
set(0, "WinBar", { link = "StatusLine" })
set(0, "WinBarNC", { link = "StatusLineNC" })
set(0, "WinSeparator", { link = "FloatBorder" })
set(0, "debugBreakpoint", { fg = c.bg, bg = c.type })
set(0, "debugPC", { link = "DiffDelete" })

-- Plugins
set(0, "CmpGhostText", { link = "NonText" })
set(0, "CmpItemAbbr", { link = "@variable" })
set(0, "CmpItemAbbrDeprecated", { link = "DiagnosticDeprecated" })
set(0, "CmpItemAbbrMatch", { link = "WarningMsg" })
set(0, "CmpItemAbbrMatchFuzzy", { link = "WarningMsg" })
set(0, "CmpItemKind", { link = "NonText" })
set(0, "CmpItemMenu", { link = "Pmenu" })
set(0, "DiffviewDiffDeleteDim", { link = "Whitespace" })
set(0, "DiffviewFilePanelSelected", { link = "WarningMsg" })
set(0, "FzfLuaBorder", { link = "FloatBorder" })
set(0, "NeotestAdapterName", { link = "Title" })
set(0, "NeotestDir", { link = "Directory" })
set(0, "NeotestFailed", { link = "Removed" })
set(0, "NeotestFile", { link = "Directory" })
set(0, "NeotestFocused", { link = "WarningMsg" })
set(0, "NeotestIndent", { link = "NonText" })
set(0, "NeotestMarked", { link = "Changed" })
set(0, "NeotestNamespace", { link = "@function.call" })
set(0, "NeotestPassed", { link = "Added" })
set(0, "NeotestRunning", { link = "DiagnosticHint" })
set(0, "NeotestSkipped", { link = "DiagnosticWarn" })
set(0, "NeotestTarget", { link = "DiagnosticHint" })
set(0, "NeotestUnknown", { link = "NonText" })
set(0, "NeotestWatching", { link = "DiagnosticWarn" })
set(0, "TreesitterContext", { link = "CursorLine" })
set(0, "TreesitterContextLineNumber", { link = "Folded" })
set(0, "diffAdded", { link = "@diff.plus" })
set(0, "diffRemoved", { link = "@diff.minus" })
