# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

git:
  autoFetch: false
  autoRefresh: false
  overrideGpg: true
  paging:
    colorArg: always
    pager: delta --paging=never
gui:
  nerdFontsVersion: '3'
  showBottomLine: false
  theme:
    selectedLineBgColor:
      - "#333738"
os:
  editPreset: nvim
customCommands:
  - key: X
    context: global
    command: fish -c gc
    description: Cleanup local git files.
    loadingText: Cleaning up
    output: log
promptToReturnFromSubprocess: false
