git:
  overrideGpg: true
  paging:
    colorArg: always
    pager: delta --dark --paging=never --tabs=4
gui:
  showBottomLine: false
  theme:
    activeBorderColor:
      - '#a6e3a1'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    selectedRangeBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#a6e3a1'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
os:
  editPreset: nvim

customCommands:
  - key: X
    context: global
    command: fish -c gc
    description: Cleanup local git files.
    loadingText: Cleaning up
    stream: true
