git:
  autoFetch: false
  autoRefresh: false
  overrideGpg: true
  paging:
    colorArg: always
    pager: delta --dark --paging=never --tabs=4
gui:
  showBottomLine: false
  theme:
    selectedLineBgColor:
      - '#393836'
    selectedRangeBgColor:
      - '#393836'
os:
  editPreset: nvim

customCommands:
  - key: X
    context: global
    command: fish -c gc
    description: Cleanup local git files.
    loadingText: Cleaning up
    stream: true

promptToReturnFromSubprocess: false
