include=/usr/share/foot/themes/nvim

font-size-adjustment=4
font=Iosevka Custom:size=13, Symbols Nerd Font:size=12
resize-by-cells=no

[mouse]
hide-when-typing=yes

[key-bindings]
spawn-terminal=Control+n
pipe-scrollback=[sh -c "f=$(mktemp) && cat - > $f && foot nvim $f; rm $f"] Control+Shift+b

# vim: cms=#\ %s
