include=/usr/share/foot/themes/nvim

font-size-adjustment=4
font=Maple Mono NF:size=11.3
resize-by-cells=no

[mouse]
hide-when-typing=yes

[key-bindings]
spawn-terminal=Control+n
pipe-scrollback=[sh -c "f=$(mktemp) && cat - > $f && foot nvim $f; rm $f"] Control+Shift+b

# vim: cms=#\ %s
