-- Based on https://github.com/rebelot/kanagawa.nvim

local M = {
	bg = "#1F1F28",
	bg_cursorline = "#363646",
	bg_float = "#16161D",
	bg_visual = "#2D4F67",
	bg_fold = "#263748",
	comment = "#727169",
	diag_error = "#E82424",
	diag_hint = "#6A9589",
	diag_info = "#658594",
	diag_warn = "#FF9E3B",
	diff_bg_add = "#2B3328",
	diff_bg_change = "#29293B",
	diff_bg_delete = "#43242B",
	diff_bg_text = "#5C3B34",
	diff_add = "#76946A",
	diff_change = "#DCA561",
	diff_delete = "#C34043",
	fg = "#D3CEC0",
	fg_border = "#54546D",
	func = "#7E9CD8",
	identifier = "#E6C384",
	keyword = "#957FB8",
	number = "#D27E99",
	operator = "#C0A36E",
	ret = "#E46876",
	special = "#938AA9",
	special1 = "#7FB4CA",
	string = "#98BB6C",
	type = "#7AA89F",
}

local set = vim.api.nvim_set_hl

-- Built in
set(0, "@attribute", { link = "Constant" })
set(0, "@comment.error", { fg = M.fg, bg = M.diag_error, bold = true })
set(0, "@comment.note", { fg = M.bg, bg = M.diag_hint, bold = true })
set(0, "@comment.warning", { fg = M.bg, bg = M.diag_warn, bold = true })
set(0, "@constructor", { fg = M.special1 })
set(0, "@constructor.lua", { fg = M.keyword })
set(0, "@diff.delta", { fg = M.diff_change })
set(0, "@diff.minus", { fg = M.diff_delete })
set(0, "@diff.plus", { fg = M.diff_add })
set(0, "@keyword.exception", { fg = M.ret, bold = true })
set(0, "@keyword.import", { link = "PreProc" })
set(0, "@keyword.luap", { link = "@string.regex" })
set(0, "@keyword.operator", { fg = M.operator, bold = true })
set(0, "@keyword.return", { fg = M.ret, italic = true })
set(0, "@lsp.mod.readonly", { link = "Constant" })
set(0, "@lsp.mod.typeHint", { link = "Type" })
set(0, "@lsp.type.builtinConstant", { link = "@constant.builtin" })
set(0, "@lsp.type.comment", { fg = "none" })
set(0, "@lsp.type.macro", { link = "Macro" })
set(0, "@lsp.type.magicFunction", { link = "@function.builtin" })
set(0, "@lsp.type.method", { link = "@function.method" })
set(0, "@lsp.type.namespace", { link = "@module" })
set(0, "@lsp.type.parameter", { link = "@variable.parameter" })
set(0, "@lsp.type.selfParameter", { link = "@variable.builtin" })
set(0, "@lsp.type.variable", { fg = "none" })
set(0, "@lsp.typemod.function.builtin", { link = "@function.builtin" })
set(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
set(0, "@lsp.typemod.function.readonly", { fg = M.func, bold = true })
set(0, "@lsp.typemod.keyword.documentation", { link = "Special" })
set(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
set(0, "@lsp.typemod.operator.controlFlow", { link = "@keyword.exception" })
set(0, "@lsp.typemod.operator.injected", { link = "Operator" })
set(0, "@lsp.typemod.string.injected", { link = "String" })
set(0, "@lsp.typemod.variable.defaultLibrary", { link = "Special" })
set(0, "@lsp.typemod.variable.global", { link = "Constant" })
set(0, "@lsp.typemod.variable.injected", { link = "@variable" })
set(0, "@lsp.typemod.variable.static", { link = "Constant" })
set(0, "@markup.environment", { link = "Keyword" })
set(0, "@markup.heading", { link = "Function" })
set(0, "@markup.italic", { italic = true })
set(0, "@markup.link.url", { link = "@string.special.url" })
set(0, "@markup.math", { link = "Constant" })
set(0, "@markup.quote", { link = "@variable.parameter" })
set(0, "@markup.raw", { link = "String" })
set(0, "@markup.strikethrough", { strikethrough = true })
set(0, "@markup.strong", { bold = true })
set(0, "@markup.underline", { underline = true })
set(0, "@operator", { link = "Operator" })
set(0, "@punctuation.bracket", { fg = M.fg })
set(0, "@punctuation.delimiter", { fg = M.fg })
set(0, "@punctuation.special", { fg = M.special1 })
set(0, "@string.escape", { fg = M.operator, bold = true })
set(0, "@string.regexp", { fg = M.operator })
set(0, "@string.special.symbol", { fg = M.identifier })
set(0, "@string.special.url", { fg = M.special1 })
set(0, "@tag.attribute", { fg = M.identifier })
set(0, "@tag.delimiter", { fg = M.fg })
set(0, "@variable", { fg = M.fg })
set(0, "@variable.builtin", { fg = M.ret, italic = true })
set(0, "@variable.member", { fg = M.identifier })
set(0, "@variable.parameter", { fg = M.fg })
set(0, "Bold", { bold = true })
set(0, "Boolean", { fg = M.number })
set(0, "Character", { link = "String" })
set(0, "ColorColumn", { bg = M.bg })
set(0, "Comment", { fg = M.comment, italic = true })
set(0, "Conceal", { fg = M.special, bold = true })
set(0, "Constant", { fg = M.fg })
set(0, "CurSearch", { fg = M.fg, bg = M.bg_visual, bold = true })
set(0, "Cursor", { fg = M.bg, bg = M.fg })
set(0, "CursorColumn", { link = "CursorLine" })
set(0, "CursorIM", { link = "Cursor" })
set(0, "CursorLine", { bg = M.bg_cursorline })
set(0, "CursorLineNr", { fg = M.diag_warn, bg = M.bg, bold = true })
set(0, "Delimiter", { fg = M.fg })
set(0, "DiagnosticError", { fg = M.diag_error })
set(0, "DiagnosticFloatingError", { fg = M.diag_error })
set(0, "DiagnosticFloatingHint", { fg = M.diag_hint })
set(0, "DiagnosticFloatingInfo", { fg = M.diag_info })
set(0, "DiagnosticFloatingOk", { fg = M.string })
set(0, "DiagnosticFloatingWarn", { fg = M.diag_warn })
set(0, "DiagnosticHint", { fg = M.diag_hint })
set(0, "DiagnosticInfo", { fg = M.diag_info })
set(0, "DiagnosticOk", { fg = M.string })
set(0, "DiagnosticSignError", { fg = M.diag_error, bg = M.bg })
set(0, "DiagnosticSignHint", { fg = M.diag_hint, bg = M.bg })
set(0, "DiagnosticSignInfo", { fg = M.diag_info, bg = M.bg })
set(0, "DiagnosticSignWarn", { fg = M.diag_warn, bg = M.bg })
set(0, "DiagnosticUnderlineError", { undercurl = true, sp = M.diag_error })
set(0, "DiagnosticUnderlineHint", { undercurl = true, sp = M.diag_hint })
set(0, "DiagnosticUnderlineInfo", { undercurl = true, sp = M.diag_info })
set(0, "DiagnosticUnderlineWarn", { undercurl = true, sp = M.diag_warn })
set(0, "DiagnosticVirtualTextError", { link = "DiagnosticError" })
set(0, "DiagnosticVirtualTextHint", { link = "DiagnosticHint" })
set(0, "DiagnosticVirtualTextInfo", { link = "DiagnosticInfo" })
set(0, "DiagnosticVirtualTextWarn", { link = "DiagnosticWarn" })
set(0, "DiagnosticWarn", { fg = M.diag_warn })
set(0, "DiffAdd", { bg = M.diff_bg_add })
set(0, "DiffChange", { bg = M.diff_bg_change })
set(0, "DiffDelete", { fg = "NONE", bg = M.diff_bg_delete })
set(0, "DiffText", { bg = M.diff_bg_text })
set(0, "Directory", { fg = M.func })
set(0, "EndOfBuffer", { fg = M.bg })
set(0, "Error", { fg = M.diag_error })
set(0, "ErrorMsg", { fg = M.diag_error })
set(0, "Exception", { fg = M.ret })
set(0, "Float", { link = "Number" })
set(0, "FloatBorder", { fg = M.fg_border, bg = M.bg_float })
set(0, "FloatFooter", { fg = M.fg_border, bg = M.bg_float })
set(0, "FloatTitle", { fg = M.special, bg = M.bg_float, bold = true })
set(0, "FoldColumn", { fg = M.fg_border, bg = M.bg })
set(0, "Folded", { fg = M.special, bg = M.bg_fold })
set(0, "Function", { fg = M.func })
set(0, "Identifier", { fg = M.identifier })
set(0, "Ignore", { link = "NonText" })
set(0, "IncSearch", { fg = M.bg, bg = M.diag_warn })
set(0, "Italic", { italic = true })
set(0, "Keyword", { fg = M.keyword, italic = true })
set(0, "LineNr", { fg = M.fg_border, bg = M.bg })
set(0, "LspCodeLens", { fg = M.comment })
set(0, "LspReferenceRead", { link = "LspReferenceText" })
set(0, "LspReferenceText", { bg = M.diff_bg_text })
set(0, "LspReferenceWrite", { bg = M.diff_bg_text, underline = true })
set(0, "LspSignatureActiveParameter", { fg = M.diag_warn })
set(0, "MatchParen", { fg = M.diag_warn, bold = true })
set(0, "ModeMsg", { fg = M.diag_warn, bold = true })
set(0, "MoreMsg", { fg = M.diag_info })
set(0, "MsgArea", vim.o.cmdheight == 0 and { link = "StatusLine" } or { fg = M.fg })
set(0, "MsgSeparator", { bg = vim.o.cmdheight == 0 and M.bg or M.bg_float })
set(0, "NonText", { fg = M.fg_border })
set(0, "Normal", { fg = M.fg, bg = M.bg })
set(0, "NormalFloat", { fg = M.fg, bg = M.bg_float })
set(0, "NormalNC", { link = "Normal" })
set(0, "Number", { fg = M.number })
set(0, "Operator", { fg = M.operator })
set(0, "Pmenu", { fg = M.fg, bg = M.bg_float })
set(0, "PmenuExtra", { fg = M.special, bg = M.bg_visual })
set(0, "PmenuExtraSel", { fg = M.special, bg = M.bg_visual })
set(0, "PmenuKind", { fg = M.fg, bg = M.bg_visual })
set(0, "PmenuKindSel", { fg = M.fg, bg = M.bg_visual })
set(0, "PmenuSbar", { bg = M.bg_float })
set(0, "PmenuSel", { fg = "NONE", bg = M.bg_cursorline })
set(0, "PmenuThumb", { bg = M.bg_cursorline })
set(0, "PreProc", { fg = M.ret })
set(0, "Question", { link = "MoreMsg" })
set(0, "QuickFixLine", { link = "CursorLine" })
set(0, "Search", { fg = M.fg, bg = M.bg_visual })
set(0, "SignColumn", { fg = M.special, bg = M.bg })
set(0, "Special", { fg = M.special1 })
set(0, "SpecialKey", { fg = M.special })
set(0, "SpellBad", { undercurl = true, sp = M.diag_error })
set(0, "SpellCap", { undercurl = true, sp = M.diag_warn })
set(0, "SpellLocal", { undercurl = true, sp = M.diag_warn })
set(0, "SpellRare", { undercurl = true, sp = M.diag_warn })
set(0, "Statement", { fg = M.keyword, bold = true })
set(0, "StatusLine", { fg = M.fg, bg = M.bg_float })
set(0, "StatusLineNC", { fg = M.fg_border, bg = M.bg_float })
set(0, "String", { fg = M.string })
set(0, "Substitute", { fg = M.fg, bg = M.diff_delete })
set(0, "TabLine", { bg = M.bg_float, fg = M.special })
set(0, "TabLineFill", { bg = M.bg })
set(0, "TabLineSel", { fg = M.fg, bg = M.bg })
set(0, "Title", { fg = M.func, bold = true })
set(0, "Todo", { fg = M.bg, bg = M.diag_info, bold = true })
set(0, "Type", { fg = M.type })
set(0, "Underlined", { fg = M.special1, underline = true })
set(0, "VertSplit", { link = "WinSeparator" })
set(0, "Visual", { bg = M.bg_visual })
set(0, "VisualNOS", { link = "Visual" })
set(0, "WarningMsg", { fg = M.diag_warn })
set(0, "Whitespace", { fg = M.bg_cursorline })
set(0, "WildMenu", { link = "Pmenu" })
set(0, "WinBar", { fg = M.fg, bg = "NONE" })
set(0, "WinBarNC", { fg = M.fg, bg = "NONE" })
set(0, "WinSeparator", { fg = M.fg_border, bg = "NONE" })
set(0, "debugBreakpoint", { fg = M.special, bg = M.bg })
set(0, "debugPC", { bg = M.diff_bg_delete })
set(0, "lCursor", { link = "Cursor" })

-- Plugins
set(0, "CmpItemKindClass", { link = "Type" })
set(0, "CmpItemKindColor", { link = "Special" })
set(0, "CmpItemKindConstant", { link = "Constant" })
set(0, "CmpItemKindConstructor", { link = "@constructor" })
set(0, "CmpItemKindCopilot", { link = "String" })
set(0, "CmpItemKindDefault", { fg = M.fg })
set(0, "CmpItemKindEnum", { link = "Type" })
set(0, "CmpItemKindEnumMember", { link = "Constant" })
set(0, "CmpItemKindEvent", { link = "Type" })
set(0, "CmpItemKindField", { link = "@variable.member" })
set(0, "CmpItemKindFile", { link = "Directory" })
set(0, "CmpItemKindFolder", { link = "Directory" })
set(0, "CmpItemKindFunction", { link = "Function" })
set(0, "CmpItemKindInterface", { link = "Type" })
set(0, "CmpItemKindKeyword", { link = "Keyword" })
set(0, "CmpItemKindMethod", { link = "@function.method" })
set(0, "CmpItemKindModule", { link = "@module" })
set(0, "CmpItemKindOperator", { link = "Operator" })
set(0, "CmpItemKindProperty", { link = "@property" })
set(0, "CmpItemKindReference", { link = "Special" })
set(0, "CmpItemKindSnippet", { link = "Special" })
set(0, "CmpItemKindStruct", { link = "Type" })
set(0, "CmpItemKindText", { fg = M.fg })
set(0, "CmpItemKindTypeParameter", { link = "Type" })
set(0, "CmpItemKindUnit", { link = "Number" })
set(0, "CmpItemKindValue", { link = "String" })
set(0, "CmpItemKindVariable", { fg = M.fg })
set(0, "DiffviewDiffDeleteDim", { fg = M.bg_cursorline })
set(0, "FzfLuaBorder", { link = "FloatBorder" })
set(0, "FzfLuaNormal", { link = "NormalFloat" })
set(0, "FzfLuaPreviewNormal", { link = "Normal" })
set(0, "FzfLuaTitle", { link = "FloatTitle" })
set(0, "LazyProgressTodo", { fg = M.fg_border })
set(0, "MultiCursorCursor", { link = "Visual" })
set(0, "NeotestAdapterName", { fg = M.ret })
set(0, "NeotestDir", { fg = M.func })
set(0, "NeotestExpandMarker", { fg = M.fg, bold = true })
set(0, "NeotestFailed", { fg = M.diag_error })
set(0, "NeotestFile", { fg = M.func })
set(0, "NeotestFocused", { bold = true, underline = true })
set(0, "NeotestIndent", { fg = M.special, bold = true })
set(0, "NeotestMarked", { fg = M.diag_warn, italic = true })
set(0, "NeotestNamespace", { fg = M.func })
set(0, "NeotestPassed", { fg = M.string })
set(0, "NeotestRunning", { fg = M.diff_change })
set(0, "NeotestSkipped", { fg = M.special1 })
set(0, "NeotestTarget", { fg = M.ret })
set(0, "NeotestTest", { fg = M.fg })
set(0, "NeotestUnknown", { fg = M.comment })
set(0, "NeotestWatching", { fg = M.diff_change })
set(0, "NeotestWinSelect", { fg = M.diag_hint })
set(0, "OilDirHidden", { link = "OilDir" })
set(0, "OilFileHidden", { link = "OilFile" })
set(0, "OilLinkHidden", { link = "OilLink" })
set(0, "OilLinkTargetHidden", { link = "OilLinkTarget" })
set(0, "OilOrphanLinkHidden", { link = "OilOrphanLink" })
set(0, "OilOrphanLinkTargetHidden", { link = "OilOrphanLinkTarget" })
set(0, "OilSocketHidden", { link = "OilSocket" })
set(0, "TreesitterContextLineNumber", { fg = M.fg_border, bg = M.bg_float })
set(0, "diffAdded", { fg = M.diff_add })
set(0, "diffChanged", { fg = M.diff_change })
set(0, "diffDeleted", { fg = M.diff_delete })
set(0, "diffNewFile", { fg = M.diff_add })
set(0, "diffOldFile", { fg = M.diff_delete })
set(0, "diffRemoved", { fg = M.diff_delete })
