- name: Bitwarden
  identifier:
    kind: Exe
    id: Bitwarden.exe
    matching_strategy: Equals
  options:
    - tray_and_multi_window
- name: Calculator
  identifier:
    kind: Title
    id: Calculator
    matching_strategy: Equals
  float_identifiers:
    - kind: Title
      id: Calculator
      matching_strategy: Equals
- name: Discord
  identifier:
    kind: Exe
    id: Discord.exe
    matching_strategy: Equals
  options:
    - tray_and_multi_window
    - layered
- name: Epic Games Launcher
  identifier:
    kind: Exe
    id: EpicGamesLauncher.exe
    matching_strategy: Equals
  options:
    - tray_and_multi_window
- name: Mozilla Firefox
  identifier:
    kind: Exe
    id: firefox.exe
    matching_strategy: Equals
  options:
    - object_name_change
    - tray_and_multi_window
  float_identifiers:
    - kind: Class
      id: MozillaTaskbarPreviewClass
      matching_strategy: Legacy
    - - kind: Title
        id: Picture-in-Picture
        matching_strategy: Equals
      - kind: Exe
        id: firefox.exe
        matching_strategy: Equals
- name: PowerToys
  identifier:
    kind: Exe
    id: PowerToys.exe
    matching_strategy: Equals
  float_identifiers:
    - kind: Exe
      id: PowerToys.ColorPickerUI.exe
      matching_strategy: Equals
    - kind: Exe
      id: PowerToys.CropAndLock.exe
      matching_strategy: Equals
    - kind: Exe
      id: PowerToys.ImageResizer.exe
      matching_strategy: Equals
    - kind: Exe
      id: PowerToys.Peek.UI.exe
      matching_strategy: Equals
    - kind: Exe
      id: PowerToys.PowerLauncher.exe
      matching_strategy: Equals
    - kind: Exe
      id: PowerToys.PowerAccent.exe
      matching_strategy: Equals
- name: Slack
  identifier:
    kind: Exe
    id: slack.exe
    matching_strategy: Equals
  options:
    - tray_and_multi_window
  float_identifiers:
    - kind: Class
      id: Chrome_RenderWidgetHostHWND
      matching_strategy: Legacy
- name: SnippingTool
  identifier:
    kind: Exe
    id: SnippingTool.exe
    matching_strategy: Equals
  float_identifiers:
    - kind: Exe
      id: SnippingTool.exe
      matching_strategy: Equals
- name: Steam
  identifier:
    kind: Class
    id: vguiPopupWindow
    matching_strategy: Legacy
  float_identifiers:
    - - kind: Exe
        id: steamwebhelper.exe
        matching_strategy: Equals
      - kind: Title
        id: Steam
        matching_strategy: DoesNotEqual
- name: Steam Beta
  identifier:
    kind: Class
    id: SDL_app
    matching_strategy: Legacy
  options:
    - tray_and_multi_window
  float_identifiers:
    - kind: Title
      id: notificationtoasts_
      matching_strategy: Legacy
- name: SystemSettings
  identifier:
    kind: Exe
    id: SystemSettings.exe
    matching_strategy: Equals
  float_identifiers:
    - kind: Class
      id: Shell_Dialog
      matching_strategy: Legacy
- name: Task Manager
  identifier:
    kind: Exe
    id: Taskmgr.exe
    matching_strategy: Equals
  float_identifiers:
    - kind: Class
      id: TaskManagerWindow
      matching_strategy: Legacy
- name: Telegram
  identifier:
    kind: Exe
    id: Telegram.exe
    matching_strategy: Equals
  options:
    - tray_and_multi_window
- name: Windows Console (conhost.exe)
  identifier:
    kind: Class
    id: ConsoleWindowClass
    matching_strategy: Equals
  options:
    - force
- name: Windows Explorer
  identifier:
    kind: Exe
    id: explorer.exe
    matching_strategy: Equals
  float_identifiers:
    - kind: Class
      id: OperationStatusWindow
      matching_strategy: Legacy
    - kind: Title
      id: Control Panel
      matching_strategy: Legacy
- name: Windows Installer
  identifier:
    kind: Exe
    id: msiexec.exe
    matching_strategy: Equals
  float_identifiers:
    - kind: Exe
      id: msiexec.exe
      matching_strategy: Equals
- name: Windows Update Standalone Installer
  identifier:
    kind: Exe
    id: wusa.exe
    matching_strategy: Equals
  float_identifiers:
    - kind: Exe
      id: wusa.exe
      matching_strategy: Equals
- name: Zebar
  identifier:
    kind: Exe
    id: Zebar.exe
    matching_strategy: Equals
  float_identifiers:
    - kind: Exe
      id: Zebar.exe
      matching_strategy: Equals
- name: Zoom
  identifier:
    kind: Exe
    id: Zoom.exe
    matching_strategy: Equals
  float_identifiers:
    - kind: Exe
      id: Zoom.exe
      matching_strategy: Equals
- name: mpv
  identifier:
    kind: Class
    id: mpv
    matching_strategy: Legacy
  options:
    - object_name_change
- name: qBittorrent
  identifier:
    kind: Exe
    id: qbittorrent.exe
    matching_strategy: Equals
  options:
    - tray_and_multi_window
