vim.pack.add({
	"https://github.com/nvim-treesitter/nvim-treesitter",
	"https://github.com/nvim-treesitter/nvim-treesitter-textobjects",
	"https://github.com/nvim-treesitter/nvim-treesitter-context",
	"https://github.com/nvim-mini/mini.surround",
	"https://github.com/jake-stewart/multicursor.nvim",
	"https://github.com/ibhagwan/fzf-lua",
	"https://github.com/sindrets/diffview.nvim",
	"https://github.com/hrsh7th/nvim-cmp",
	"https://github.com/hrsh7th/cmp-buffer",
	"https://github.com/hrsh7th/cmp-nvim-lsp",
	"https://github.com/stevearc/conform.nvim",
	"https://github.com/stevearc/oil.nvim",
	"https://github.com/nvim-lua/plenary.nvim",
	"https://github.com/nvim-neotest/nvim-nio",
	"https://github.com/nvim-neotest/neotest",
	"https://github.com/fredrikaverpil/neotest-golang",
	"https://github.com/mfussenegger/nvim-dap",
})

require("plugins.treesitter")
require("plugins.editor")
require("plugins.finder")
require("plugins.git")
require("plugins.lsp")
require("plugins.test")
