local theme = require("kanagawa.colors").setup().theme

return {
	black = theme.term[1],
	red = theme.term[2],
	green = theme.term[3],
	yellow = theme.term[4],
	blue = theme.term[5],
	magenta = theme.term[6],
	cyan = theme.term[7],
	white = theme.term[8],
	bright_black = theme.term[9],
	bright_red = theme.term[10],
	bright_green = theme.term[11],
	bright_yellow = theme.term[12],
	bright_blue = theme.term[13],
	bright_magenta = theme.term[14],
	bright_cyan = theme.term[15],
	bright_white = theme.term[16],
	orange = theme.term[17],
	peach = theme.term[18],
	bg = theme.ui.bg,
	bg_p1 = theme.ui.bg_p1,
	fg = theme.ui.fg,
}
