commandTemplates:
  dockerCompose: docker compose
gui:
  returnImmediately: true
  showBottomLine: false
  theme:
    selectedLineBgColor:
      - '#393836'
    selectedRangeBgColor:
      - '#393836'
