include vague.conf

confirm_os_window_close 0
enabled_layouts splits,stack
macos_option_as_alt yes
placement_strategy top

font_family family="Iosevka Custom"
font_size 13
text_composition_strategy legacy

map alt+d launch --location=hsplit --cwd=current
map alt+n launch --location=vsplit --cwd=current

map alt+h neighboring_window left
map alt+j neighboring_window down
map alt+k neighboring_window up
map alt+l neighboring_window right
map alt+f toggle_layout stack

map alt+shift+h move_window left
map alt+shift+j move_window down
map alt+shift+k move_window up
map alt+shift+l move_window right

map ctrl+alt+h resize_window narrower 4
map ctrl+alt+j resize_window shorter 4
map ctrl+alt+k resize_window taller 4
map ctrl+alt+l resize_window wider 4
map ctrl+alt+r resize_window reset

map ctrl+equal change_font_size all +4
map ctrl+minus change_font_size all -4
map ctrl+0 change_font_size all 0

mouse_map left click ungrabbed
mouse_map ctrl+left click ungrabbed mouse_handle_click selection link prompt
