vim.cmd("colorscheme vague-custom")
require("options")
require("statusline")
require("tabline")

vim.schedule(function()
	require("keymaps")
	require("autocmds")
	require("lsp")
	require("git")
	require("docker")
	require("session")

	require("plugins")
end)
